version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    command: expo start --tunnel
    volumes:
      - ./app:/opt/app
    ports:
      - 19000:19000
      - 19002:19002
      - 19006:19006
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=${EXPO_DEVTOOLS_LISTEN_ADDRESS}
      - REACT_NATIVE_PACKAGER_HOSTNAME=${REACT_NATIVE_PACKAGER_HOSTNAME}

